clear;
%构建时域函数
figure(1);
dt=0.0002;
t=-0.4:dt:0.4;
xt=0.02*(1+0.4*cos(60*pi.*t))./(0.0001+t.^2);
subplot(3,1,1)
plot(t,xt,'LineWidth',1) 
title('原时域信号x(t)','Fontsize',16)
xlabel('t')
ylabel('x(t)')

%xt的频谱
figure(1)
N_fft=length(t);
df=1/(N_fft*dt);
Faxis=df*((1:N_fft)-N_fft/2);
Fshift=dt*fftshift(fft(xt));
theta=angle(Fshift)/pi*180;
subplot(3,1,2)
plot(Faxis,abs(Fshift),'LineWidth',1)
title('x(t)的幅度谱','Fontsize',16)
xlabel('Frequency')
ylabel('|F|')
subplot(3,1,3)
plot(Faxis,theta,'LineWidth',1)
title('x(t)的相位谱','Fontsize',16)
xlabel('Frequency')
ylabel('\theta')

%利用定义的函数进行复用
mysample(80,2);
mysample(200,5);